name: face_recognition
description: A Flutter app that analyzes a user's face and recommends beauty cosmetics products.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+3
  image: ^4.1.3
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_commons: ^0.9.0
  tflite_flutter: ^0.11.0
  logger: ^2.4.0
  url_launcher: ^6.0.17
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  permission_handler: ^11.3.1
  camera: ^0.10.5+2
  
  # Add http dependency for making API calls
  http: ^1.2.2

  fl_chart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo.png
    - assets/
