// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyfEIH5y0rm36Zt31IOjIKjvB_O9t7n4',
    appId: '1:830659242888:web:ffcc785dbe0c62edefa83d',
    messagingSenderId: '830659242888',
    projectId: 'facial-recognition-61c66',
    authDomain: 'facial-recognition-61c66.firebaseapp.com',
    storageBucket: 'facial-recognition-61c66.appspot.com',
    measurementId: 'G-ZRJ5043WL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgiugWcpNexxFNjwxmnn3JhOWSluovyik',
    appId: '1:830659242888:android:c94726a4981554b0efa83d',
    messagingSenderId: '830659242888',
    projectId: 'facial-recognition-61c66',
    storageBucket: 'facial-recognition-61c66.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Ic2ZlYiQcufcG1J-aEm74SPSX_1rF8k',
    appId: '1:830659242888:ios:e81e63bd3f1ce20aefa83d',
    messagingSenderId: '830659242888',
    projectId: 'facial-recognition-61c66',
    storageBucket: 'facial-recognition-61c66.appspot.com',
    iosBundleId: 'com.example.faceRecognitionWithImages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHyfEIH5y0rm36Zt31IOjIKjvB_O9t7n4',
    appId: '1:830659242888:web:f3adbeb8a7f8ef09efa83d',
    messagingSenderId: '830659242888',
    projectId: 'facial-recognition-61c66',
    authDomain: 'facial-recognition-61c66.firebaseapp.com',
    storageBucket: 'facial-recognition-61c66.appspot.com',
    measurementId: 'G-3NEXKRBFEZ',
  );
}
